#!/usr/bin/env sh
# Install the /vmodel command, skills and review agents into Claude Code (~/.claude).
# Usage: ./scripts/install.sh [--check] [--codex]
set -eu

check=0
codex=0
for arg in "$@"; do
    case "$arg" in
        --check) check=1 ;;
        --codex) codex=1 ;;
        -h|--help) sed -n '2,3p' "$0" | sed 's/^# //'; exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
claude_root="${CLAUDE_HOME:-$HOME/.claude}"

install_file() {
    src=$1
    dest=$2
    if [ -f "$dest" ] && cmp -s "$src" "$dest"; then
        echo "  current   $dest"
        return
    fi
    if [ -f "$dest" ]; then verb='overwrite'; else verb='add      '; fi
    if [ "$check" -eq 1 ]; then
        echo "  would ${verb% } $dest"
        return
    fi
    mkdir -p "$(dirname -- "$dest")"
    cp -- "$src" "$dest"
    echo "  $verb $dest"
}

echo 'Commands:'
for file in "$repo_root"/commands/*.md; do
    install_file "$file" "$claude_root/commands/$(basename -- "$file")"
done

echo 'Agents:'
for file in "$repo_root"/agents/*.md; do
    install_file "$file" "$claude_root/agents/$(basename -- "$file")"
done

echo 'Skills:'
for directory in "$repo_root"/skills/*/; do
    name=$(basename -- "$directory")
    install_file "$directory/SKILL.md" "$claude_root/skills/$name/SKILL.md"
done

if [ "$codex" -eq 1 ]; then
    echo 'Codex sync:'
    codex_root="${CODEX_HOME:-$HOME/.codex}"
    for directory in "$repo_root"/skills/*/; do
        name=$(basename -- "$directory")
        link="$codex_root/skills/$name"
        target="$claude_root/skills/$name"

        if [ -L "$link" ] && [ "$(readlink -- "$link")" = "$target" ]; then
            echo "  current   $link"
            continue
        fi
        if [ -d "$link" ] && [ ! -L "$link" ] && cmp -s "$link/SKILL.md" "$target/SKILL.md"; then
            echo "  current   $link"
            continue
        fi
        # Anything else already at this path is the user's: a plain file, a
        # directory of their own, or a symlink pointing somewhere we did not
        # put it. Never destroy it -- this is the only branch that deletes.
        if [ -e "$link" ] || [ -L "$link" ]; then
            echo "  preserved $link"
            continue
        fi
        if [ "$check" -eq 1 ]; then
            echo "  would link $link (or copy if symlinks are unavailable)"
            continue
        fi

        mkdir -p "$codex_root/skills"
        if ln -s -- "$target" "$link" 2>/dev/null && [ -L "$link" ]; then
            echo "  linked    $link"
        else
            # No symlink support (e.g. Git Bash on Windows without developer mode).
            # Falls back to a copy, which does NOT track later edits to ~/.claude.
            rm -rf -- "$link"
            mkdir -p "$link"
            cp -- "$target/SKILL.md" "$link/SKILL.md"
            echo "  copied    $link (no symlink support; re-run after updating ~/.claude)"
        fi
    done
    echo '  note: Codex adapters for commands/agents are generated by scripts/sync-claude-skills.ps1 (PowerShell only).'
    echo '        On this platform, reference ~/.claude/commands and ~/.claude/agents directly.'
fi

[ "$check" -eq 1 ] && echo && echo 'Preview only. Re-run without --check to apply.'
exit 0
